uploads:
  map_upload_dir: uploads\maps
  traffic_data_dir: uploads\traffic_data
  trash_data_dir: uploads\trash_data

database:
  db_url: PLACEHOLDER_FOR_DB_URL
  db_name: trash_panda_db

logging:
  logs_dir: logs

