uploads:
  map_upload_dir: maps
  traffic_data_dir: traffic_data
  trash_data_dir: trash_data

database:
  online_mode: false
  db_username: postgres
  db_password: 12345678
  db_name: trash_panda_db
  db_host: localhost
  db_port: 6969

logging:
  logs_dir: logs

path_planning:
  

